apiVersion: kustomize.config.k8s.io/v1beta1
kind: external-secret
metadata:
  name: team1-secret
  namespace: team1-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: team1-secret
  data:
  - secretKey: db-host
    remoteRef:
      key: /team1/eks-prod/db-host
  - secretKey: db-username
    remoteRef:
      key: /team1/eks-prod/db-username
  - secretKey: db-password
    remoteRef:
      key: /team1/eks-prod/db-password
  - secretKey: db-name
    remoteRef:
      key: /team1/eks-prod/db-name
  - secretKey: jwt-secret
    remoteRef:
      key: /team1/eks-prod/jwt-secret
  - secretKey: slack-webhook-url
    remoteRef:
      key: /team1/eks-prod/slack-webhook-url
