apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: team1-app
  namespace: team1-dev
spec:
  parentRefs:
    - name: team1-gateway
      namespace: team1-dev
  # hostnames:
  #   - "team1.dev.course-registration.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: team1-app
          port: 80
