apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: team1-secret
  namespace: team1-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: team1-secret
  data:
  - secretKey: db-host
    remoteRef:
      key: /team1/eks-dev/db-host
  - secretKey: db-username
    remoteRef:
      key: /team1/eks-dev/db-username
  - secretKey: db-password
    remoteRef:
      key: /team1/eks-dev/db-password
  - secretKey: db-name
    remoteRef:
      key: /team1/eks-dev/db-name
  - secretKey: jwt-secret
    remoteRef:
      key: /team1/eks-dev/jwt-secret