apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team1-dev

resources:
- ../../base

images:
- name: nginx:1.27
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/course-service
  newTag: 14c7347bddbb414a856e5c1baa280205fb33e3a3
