apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team1-dev

resources:
- ../../base

images:
- name: nginx:1.27
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/course-service
  newTag: 3c772ea6d3d6ceb3af9cfc84e189f1c3804e090c
