apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: team1-app
  namespace: monitoring                          # Prometheus와 같은 네임스페이스
  labels:
    release: kube-prom-stack               # 설치한 Helm Release 이름
spec:
  namespaceSelector:
    matchNames:
      - team1-dev
      - team1-prod
  selector:
    matchLabels:
      app.kubernetes.io/name: team1-app           # base/service.yaml의 라벨과 일치
  endpoints:
    - port: management                           # Service에서 정의한 포트 name
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s